export const theme = {
         mainBlue: "#283593",
         navyBlue: "#2c303b",
         darkNavyBlue: "#1a1d2a",
         mint: "#03DAC5",
         darkMint: "#02AE9D",
         errorRed: "#db0b0b",
         errorText: "#1C245D",
         yellow: "#edd052",
         white: "#fff",
         darkGray: "#75767F",
         lightGray: "#D3D7DB",
         lightGrayDisabledButton: "#EFEFF3",
         grayForDashboard: "#b3b8d9",
       };