export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_ERROR: 'USERS_LOGIN_ERROR',

    LOGOUT: 'USERS_LOGOUT',

    GETUSERS_REQUEST: 'USERS_GETALL_REQUEST',
    GETUSERS_SUCCESS: 'USERS_GETALL_SUCCESS',
<<<<<<< HEAD
    GETUSERS_FAILURE: 'USERS_GETALL_FAILURE'
=======
    GETUSERS_FAILURE: 'USERS_GETALL_FAILURE',
}

export const expenseTypesConstants = {
    GETEXPENSETYPES_REQUEST: 'EXPENSETYPES_GETALL_REQUEST',
    GETEXPENSETYPES_SUCCESS: 'EXPENSETYPES_GETALL_SUCCESS',
    GETEXPENSETYPES_FAILURE: 'EXPENSETYPES_GETALL_FAILURE',
}

export const incomeTypesConstants = {
  GETINCOMETYPES_REQUEST: 'INCOMETYPES_GETALL_REQUEST',
  GETINCOMETYPES_SUCCESS: 'INCOMETYPES_GETALL_SUCCESS',
  GETINCOMETYPES_FAILURE: 'INCOMETYPES_GETALL_FAILURE',
};

export const currenciesConstants = {
    GETCURRENCIES_REQUEST: 'CURRENCIES_GETALL_REQUEST',
    GETCURRENCIES_SUCCESS: 'CURRENCIES_GETALL_SUCCESS',
    GETCURRENCIES_FAILURE: 'CURRENCIES_GETALL_FAILURE',

    GETRATES_REQUEST: 'CURRENCIES_GETRATES_REQUEST',
    GETRATES_SUCCESS: 'CURRENCIES_GETRATES_SUCCESS',
    GETRATES_FAILURE: 'CURRENCIES_GETRATES_FAILURE',
}

export const expensesConstants = {
  GETEXPENSES_REQUEST: 'EXPENSES_GETALL_REQUEST',
  GETEXPENSES_SUCCESS: 'EXPENSES_GETALL_SUCCESS',
  GETEXPENSES_FAILURE: 'EXPENSES_GETALL_FAILURE',

  ADDEXPENSE_REQUEST: 'EXPENSE_ADD_REQUEST',
  ADDEXPENSE_SUCCESS: 'EXPENSE_ADD_SUCCESS',
  ADDEXPENSE_FAILURE: 'EXPENSE_ADD_FAILURE',

  UPDATEEXPENSE_REQUEST: 'EXPENSE_UPDATE_REQUEST',
  UPDATEEXPENSE_SUCCESS: 'EXPENSE_UPDATE_SUCCESS',
  UPDATEEXPENSE_FAILURE: 'EXPENSE_UPDATE_FAILURE',

  DELETEEXPENSE_REQUEST: 'EXPENSE_DELETE_REQUEST',
  DELETEEXPENSE_SUCCESS: 'EXPENSE_DELETE_SUCCESS',
  DELETEEXPENSE_FAILURE: 'EXPENSE_DELETE_FAILURE',
};

export const incomesConstants = {
  GETINCOMES_REQUEST: 'INCOMES_GETALL_REQUEST',
  GETINCOMES_SUCCESS: 'INCOMES_GETALL_SUCCESS',
  GETINCOMES_FAILURE: 'INCOMES_GETALL_FAILURE',

  ADDINCOME_REQUEST: 'INCOME_ADD_REQUEST',
  ADDINCOME_SUCCESS: 'INCOME_ADD_SUCCESS',
  ADDINCOME_FAILURE: 'INCOME_ADD_FAILURE',

  UPDATEINCOME_REQUEST: 'INCOME_UPDATE_REQUEST',
  UPDATEINCOME_SUCCESS: 'INCOME_UPDATE_SUCCESS',
  UPDATEINCOME_FAILURE: 'INCOME_UPDATE_FAILURE',

  DELETEINCOME_REQUEST: 'INCOME_DELETE_REQUEST',
  DELETEINCOME_SUCCESS: 'INCOME_DELETE_SUCCESS',
  DELETEINCOME_FAILURE: 'INCOME_DELETE_FAILURE',
};

export const datesRangeConstants = {
  SETDATESRANGE_REQUEST: 'DATERANGE_SET_REQUEST',
  SETDATESRANGE_SUCCESS: 'DATERANGE_SET_SUCCESS',
  SETDATESRANGE_FAILURE: 'DATERANGE_SET_FAILURE',
}

export const filteredTransactionsConstants = {
  FILTEREDTRANSACTIONS_LOAD: 'FILTEREDTRANSACTIONS_LOAD',
  FILTEREDTRANSACTIONS_ADD: 'FILTEREDTRANSACTIONS_ADD'
}

export const groupedExpensesConstants = {
  GROUPEDEXPENSES_REQUEST: 'GROUPED_EXPENSES_REQUEST',
  GROUPEDEXPENSES_LOAD: 'GROUPED_EXPENSES_LOAD',
>>>>>>> c6ad148a2ecfaac525fdf265c0de8230d298eab2
}