export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_ERROR: 'USERS_LOGIN_ERROR',

    LOGOUT: 'USERS_LOGOUT',

    GETUSERS_REQUEST: 'USERS_GETALL_REQUEST',
    GETUSERS_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETUSERS_FAILURE: 'USERS_GETALL_FAILURE',
}

export const expenseTypesConstants = {
    GETEXPENSETYPES_REQUEST: 'EXPENSETYPES_GETALL_REQUEST',
    GETEXPENSETYPES_SUCCESS: 'EXPENSETYPES_GETALL_SUCCESS',
    GETEXPENSETYPES_FAILURE: 'EXPENSETYPES_GETALL_FAILURE',
}

export const incomeTypesConstants = {
  GETINCOMETYPES_REQUEST: 'INCOMETYPES_GETALL_REQUEST',
  GETINCOMETYPES_SUCCESS: 'INCOMETYPES_GETALL_SUCCESS',
  GETINCOMETYPES_FAILURE: 'INCOMETYPES_GETALL_FAILURE',
};

export const currenciesConstants = {
    GETCURRENCIES_REQUEST: 'CURRENCIES_GETALL_REQUEST',
    GETCURRENCIES_SUCCESS: 'CURRENCIES_GETALL_SUCCESS',
    GETCURRENCIES_FAILURE: 'CURRENCIES_GETALL_FAILURE',
}

export const expensesConstants = {
  GETEXPENSES_REQUEST: 'EXPENSES_GETALL_REQUEST',
  GETEXPENSES_SUCCESS: 'EXPENSES_GETALL_SUCCESS',
  GETEXPENSES_FAILURE: 'EXPENSES_GETALL_FAILURE',

  ADDEXPENSE_REQUEST: 'EXPENSE_ADD_REQUEST',
  ADDEXPENSE_SUCCESS: 'EXPENSE_ADD_SUCCESS',
  ADDEXPENSE_FAILURE: 'EXPENSE_ADD_FAILURE',

  DELETEEXPENSE_REQUEST: 'EXPENSE_DELETE_REQUEST',
  DELETEEXPENSE_SUCCESS: 'EXPENSE_DELETE_SUCCESS',
  DELETEEXPENSE_FAILURE: 'EXPENSE_DELETE_FAILURE',
};

export const incomesConstants = {
    GETINCOMES_REQUEST: 'INCOMES_GETALL_REQUEST',
    GETINCOMES_SUCCESS: 'INCOMES_GETALL_SUCCESS',
    GETINCOMES_FAILURE: 'INCOMES_GETALL_FAILURE',

    ADDINCOME_REQUEST: 'INCOME_ADD_REQUEST',
    ADDINCOME_SUCCESS: 'INCOME_ADD_SUCCESS',
    ADDINCOME_FAILURE: 'INCOME_ADD_FAILURE',
};

export const datesRangeConstants = {
    SETDATESRANGE_REQUEST: 'DATERANGE_SET_REQUEST',
    SETDATESRANGE_SUCCESS: 'DATERANGE_SET_SUCCESS',
    SETDATESRANGE_FAILURE: 'DATERANGE_SET_FAILURE',
}